#ifndef RETURN_CODE_H
#define RETURN_CODE_H

#define RC_SUCCESS 0
#define RC_FAILURE 1

#define RC_SHELL_SYNTAX_ERROR
#define RC_BUILTIN_UTILITY_ERROR 2

#define RC_OTHER_UTILITY_ERROR -1
#define RC_REDIRECTION_BUILTIN_ERROR -1
#define RC_REDIRECTION_COMPOUND_COMMANDS_ERROR -1
#define RC_REDIRECTION_FUNCTION_EXECUTION_ERROR -1
#define RC_REDIRECTION_OTHER_ERROR -1
#define RC_VARIABLE_ASSIGNMENT_ERROR -1
#define RC_EXPANSION_ERROR -1
#define RC_COMMAND_NOT_FOUND 127



#endif /* ! RETURN_CODE_H */